### ISSUE TITLE
does it implement Formatter ?

### ISSUE THREAD

**Issue by mh-cbon** [fsamin/go-dump#1]
Hi,

Does the lib provide a trait i can add to my types to implements Formatter interface so that i can do `fmt.Printf("%#v", xxx)` to pretty debug a type i know i need special handling `type yy struct { PrettyDump }`

Thanks

**Comment by fsamin** [comment]
Hi,

It does not provide such a type. In fact, it could not work because the lib could only access to `PrettyDump` fields; due to composition vs inheritance.

Here is a snippet to show it: https://play.golang.org/p/Dc6DxfY0u2

BTW you can simply do a `fmt.Printf("%s", dump.MustSdump(xxx))`

**Comment by mh-cbon** [comment]
true!
