### ISSUE TITLE
go-dump doesn't dump Stringers (eg. time.Time)

### ISSUE THREAD

**Issue by Thiht** [fsamin/go-dump#19]
Sample code: https://play.golang.org/p/Fj5f7y9eEpO

The `date` field is not dumped because it's a `time.Time`. go-dump should handle `Stringer`s.

This causes an issue with Venom's sql executor because `TIMESTAMPTZ` are returned as `time.Time`, so we cannot make assertions on these fields

**Comment by fsamin** [comment]
fixed on 5c3acfb

**Comment by Thiht** [comment]
Thanks :)
